apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: capable-stork-go 
  janus-idp.io/tekton: capable-stork-go
  backstage.io/kubernetes-id: capable-stork-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: capable-stork-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  